---
# tasks file for swarm-setup

# - name: "adding working to swarm"
#   docker_swarm:
#     state: join
#     advertise_addr: swarm-worker
#     join_token: "{{ hostvars['swarm-manager']['info']['swarm_facts']['JoinTokens']['Worker'] }}"
#     remote_addrs: [ 'swarm-manager:2377' ]

- name: Initialise swarm
  docker_swarm:
    state: present
  register: swarm_info